binary_subtractor_project:
wire start not defined [HalfSubtractor.w-]
wire start not defined [HalfSubtractor.w-]
wire start not defined [HalfSubtractor.w-]
wire start not defined [HalfSubtractor.w-]
wire start not defined [HalfSubtractor.w-]
wire start not defined [HalfSubtractor.w-]
wire start not defined [FullSubtractor.w-]
wire start not defined [FullSubtractor.w-]
wire start not defined [FullSubtractor.w-]
wire start not defined [FullSubtractor.w-]
wire start not defined [FullSubtractor.w-]
wire start not defined [FullSubtractor.w-]
wire start not defined [FullSubtractor.w-]
wire start not defined [FullSubtractor.w-]
wire start not defined [FullSubtractor.w-]
wire start not defined [FullSubtractor.w-]
wire start not defined [FullSubtractor.w-]
component `Subcircuit' not found [4BitSubtractor.Subcircuit()]
component `Subcircuit' not found [4BitSubtractor.Subcircuit()]
component `Subcircuit' not found [4BitSubtractor.Subcircuit()]
component `Subcircuit' not found [4BitSubtractor.Subcircuit()]
wire start misformatted [4BitSubtractor.wA[3..0]-FullSubtractor]
wire start misformatted [4BitSubtractor.wB[3..0]-FullSubtractor]
wire start not defined [4BitSubtractor.w-]
wire start not defined [4BitSubtractor.w-]
wire start misformatted [4BitSubtractor.wFullSubtractor-D[3..0]]
wire start misformatted [4BitSubtractor.wFullSubtractor-Bout]